### ISSUE TITLE
能否支持传入自定义短语库

### ISSUE THREAD

**Issue by ilyydy** [pengzhanbo/chinese-simple2traditional#2]
注入短语库后，`堅強`还是被转成`坚犟`。如果可以自定义短语库，处理这种转不了的就方便得多

**Comment by pengzhanbo** [comment]
可以添加相关的支持。

发现相关的 短语 转换问题，建议在 issue 描述 是 简体转繁体 或是 繁体转简体 的问题。
也可以提出 PR 修改本仓库 data 目录中的数据源件，帮助完善这个开源的项目 😄

**Comment by pengzhanbo** [comment]
检查发现该问题是由于引入的 1.x 版本的 字库中，错误的把  `犟` `強` 处理为了 繁简体映射关系，实际上 `犟` 繁简体同字。
